name: Auto Merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  check_suite:
    types: [completed]
  status: {}

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
    - name: Auto merge
      uses: actions/github-script@v5
      with:
        script: |
          const { data: pullRequest } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
          });

          if (pullRequest.user.login === 'dependabot[bot]' &&
              pullRequest.labels.find(label => label.name === 'dependencies') &&
              (pullRequest.title.startsWith('chore(deps): bump') || pullRequest.title.startsWith('fix(deps): bump'))) {
            const mergeMethod = 'squash'; // Change this to 'merge' or 'rebase' as necessary
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              merge_method: mergeMethod,
            });
            console.log(`Pull request #${context.issue.number} merged!`);
          } else {
            console.log('Conditions not met for auto-merging.');
          }
        github-token: ${{ secrets.GITHUB_TOKEN }}
