# Make sure that auto-merge is enabled in GitHub repository:
# https://stackoverflow.com/a/76906064
#
# Make sure that GitHub Actions are allowed to approve pull requests:
# https://stackoverflow.com/a/73155199

name: Auto Merge Dependabot PRs

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          # Personal access token, from: https://github.com/settings/tokens
          github-token: ${{ secrets.TOKEN }}
